version: '3'

services:
  go-proxy-bingai:
    image: zklcdc/go-proxy-bingai:latest-with-pass
    container_name: go-proxy-bingai-with-pass
    restart: always
    ports:
      - 8080:8080
      - 45678:45678
    environment:
      # - BING_BASE_URL=https://www.bing.com
      # - SYDNEY_BASE_URL=https://sydney.bing.com
      # - HTTP_PROXY=http://172.17.0.1:18080
      # - HTTPS_PROXY=http://172.17.0.1:18080
      # - Go_Proxy_BingAI_USER_TOKEN_1=xxx
      # - Go_Proxy_BingAI_USER_TOKEN_2=xxx
      # - USER_KievRPSSecAuth=xxx
      # - USER_RwBf=xxx
      # - USER_MUID=xxx
      - APIKEY=sk-xxx
      - CF_ZERO_TRUST_TOKEN=CF_ZERO_TRUST_TOKEN
